//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.20 at 04:29:50 PM CDT 
//


package com.salesmanager.core.business.services.tax.ecosio.vrbl.vertexinc.vrbl.extensioncomponent._1;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartyLegalEntityExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartyLegalEntityExtensionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:vertexinc:vrbl:ExtensionComponent:1}BaseCapital" minOccurs="0"/>
 *         &lt;element ref="{urn:vertexinc:vrbl:ExtensionComponent:1}BusinessRegistrationProvinceCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartyLegalEntityExtensionType", propOrder = {
    "baseCapital",
    "businessRegistrationProvinceCode"
})
public class PartyLegalEntityExtensionType {

    @XmlElement(name = "BaseCapital")
    protected BigDecimal baseCapital;
    @XmlElement(name = "BusinessRegistrationProvinceCode")
    protected String businessRegistrationProvinceCode;

    /**
     * Gets the value of the baseCapital property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBaseCapital() {
        return baseCapital;
    }

    /**
     * Sets the value of the baseCapital property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBaseCapital(BigDecimal value) {
        this.baseCapital = value;
    }

    /**
     * Gets the value of the businessRegistrationProvinceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessRegistrationProvinceCode() {
        return businessRegistrationProvinceCode;
    }

    /**
     * Sets the value of the businessRegistrationProvinceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessRegistrationProvinceCode(String value) {
        this.businessRegistrationProvinceCode = value;
    }

}
