//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.08 at 07:11:38 PM UTC 
//


package com.salesmanager.core.business.services.tax.ecosio.vrbl.vertexinc.vrbl.extensioncomponent._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PayeePartyExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PayeePartyExtensionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:vertexinc:vrbl:ExtensionComponent:1}PersonConfirmingPayment" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayeePartyExtensionType", propOrder = {
    "personConfirmingPayment"
})
public class PayeePartyExtensionType {

    @XmlElement(name = "PersonConfirmingPayment")
    protected PersonConfirmingPaymentType personConfirmingPayment;

    /**
     * Gets the value of the personConfirmingPayment property.
     * 
     * @return
     *     possible object is
     *     {@link PersonConfirmingPaymentType }
     *     
     */
    public PersonConfirmingPaymentType getPersonConfirmingPayment() {
        return personConfirmingPayment;
    }

    /**
     * Sets the value of the personConfirmingPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonConfirmingPaymentType }
     *     
     */
    public void setPersonConfirmingPayment(PersonConfirmingPaymentType value) {
        this.personConfirmingPayment = value;
    }

}
