//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.08 at 07:11:38 PM UTC
//


package com.salesmanager.core.business.services.tax.ecosio.vrbl.vertexinc.vrbl.extensioncomponent._1;

import javax.xml.bind.annotation.*;

import com.salesmanager.core.business.services.tax.ecosio.vrbl.oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.AmountType;


/**
 * <p>Java class for PriceExtensionType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PriceExtensionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:vertexinc:vrbl:ExtensionComponent:1}BelowMarketValueSupplyIndicator" minOccurs="0"/>
 *         &lt;element ref="{urn:vertexinc:vrbl:ExtensionComponent:1}PriceAmountBeforeAllowanceCharge" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlRootElement(name="PriceExtension")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PriceExtensionType", propOrder = {
        "belowMarketValueSupplyIndicator",
        "priceAmountBeforeAllowanceCharge"
})
public class PriceExtensionType {

    @XmlElement(name = "BelowMarketValueSupplyIndicator")
    protected Boolean belowMarketValueSupplyIndicator;
    @XmlElement(name = "PriceAmountBeforeAllowanceCharge")
    protected AmountType priceAmountBeforeAllowanceCharge;

    /**
     * Gets the value of the belowMarketValueSupplyIndicator property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isBelowMarketValueSupplyIndicator() {
        return belowMarketValueSupplyIndicator;
    }

    /**
     * Sets the value of the belowMarketValueSupplyIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setBelowMarketValueSupplyIndicator(Boolean value) {
        this.belowMarketValueSupplyIndicator = value;
    }

    /**
     * Gets the value of the priceAmountBeforeAllowanceCharge property.
     *
     * @return
     *     possible object is
     *     {@link AmountType }
     *
     */
    public AmountType getPriceAmountBeforeAllowanceCharge() {
        return priceAmountBeforeAllowanceCharge;
    }

    /**
     * Sets the value of the priceAmountBeforeAllowanceCharge property.
     *
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *
     */
    public void setPriceAmountBeforeAllowanceCharge(AmountType value) {
        this.priceAmountBeforeAllowanceCharge = value;
    }

}

