//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.08 at 07:11:38 PM UTC 
//


package com.salesmanager.core.business.services.tax.ecosio.vrbl.vertexinc.vrbl.extensioncomponent._1;

import java.math.BigDecimal;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for PriceExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PriceExtensionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:vertexinc:vrbl:ExtensionComponent:1}PriceAmountBeforeAllowanceCharge" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="PriceExtension")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PriceExtension", propOrder = {
    "priceAmountBeforeAllowanceCharge"
})
public class PriceExtensionType {

    @XmlElement(name = "PriceAmountBeforeAllowanceCharge")
    protected BigDecimal priceAmountBeforeAllowanceCharge;

    /**
     * Gets the value of the priceAmountBeforeAllowanceCharge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPriceAmountBeforeAllowanceCharge() {
        return priceAmountBeforeAllowanceCharge;
    }

    /**
     * Sets the value of the priceAmountBeforeAllowanceCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPriceAmountBeforeAllowanceCharge(BigDecimal value) {
        this.priceAmountBeforeAllowanceCharge = value;
    }

}
