//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.08 at 07:11:38 PM UTC 
//


package com.salesmanager.core.business.services.tax.ecosio.vrbl.vertexinc.vrbl.extensioncomponent._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoutingDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoutingDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:vertexinc:vrbl:ExtensionComponent:1}Sender"/>
 *         &lt;element ref="{urn:vertexinc:vrbl:ExtensionComponent:1}Receiver"/>
 *         &lt;element ref="{urn:vertexinc:vrbl:ExtensionComponent:1}ReceiverDetails" minOccurs="0"/>
 *         &lt;element ref="{urn:vertexinc:vrbl:ExtensionComponent:1}TestFlag" minOccurs="0"/>
 *         &lt;element ref="{urn:vertexinc:vrbl:ExtensionComponent:1}FinalDeliveryChannel" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoutingDetailsType", propOrder = {
    "sender",
    "receiver",
    "receiverDetails",
    "testFlag",
    "finalDeliveryChannel"
})
public class RoutingDetailsType {

    @XmlElement(name = "Sender", required = true)
    protected String sender;
    @XmlElement(name = "Receiver", required = true)
    protected String receiver;
    @XmlElement(name = "ReceiverDetails")
    protected String receiverDetails;
    @XmlElement(name = "TestFlag")
    protected Boolean testFlag;
    @XmlElement(name = "FinalDeliveryChannel")
    protected FinalDeliveryChannelType finalDeliveryChannel;

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSender(String value) {
        this.sender = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiver(String value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the receiverDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverDetails() {
        return receiverDetails;
    }

    /**
     * Sets the value of the receiverDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverDetails(String value) {
        this.receiverDetails = value;
    }

    /**
     * Setting the TestFlag to "true" marks the document as a test. If the TestFlag is not provided, it is considered to be set to "false".
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTestFlag() {
        return testFlag;
    }

    /**
     * Sets the value of the testFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTestFlag(Boolean value) {
        this.testFlag = value;
    }

    /**
     * Gets the value of the finalDeliveryChannel property.
     * 
     * @return
     *     possible object is
     *     {@link FinalDeliveryChannelType }
     *     
     */
    public FinalDeliveryChannelType getFinalDeliveryChannel() {
        return finalDeliveryChannel;
    }

    /**
     * Sets the value of the finalDeliveryChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinalDeliveryChannelType }
     *     
     */
    public void setFinalDeliveryChannel(FinalDeliveryChannelType value) {
        this.finalDeliveryChannel = value;
    }

}
